language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
scripts:
  - npm run test
deploy:
  - provider: script
    script: npm version from-git --allow-same-version --force
    on:
      tags: true
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    on:
      tags: true
    skip_cleanup: true
